import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";


export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','400','500', '600', '700', '800', '900']
})

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
